services:
  analysis-nb-server:
    image: farrandi/english-score-predictor:main
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
