services:
  analysis-nb-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      PASSWORD: password
