services:
  analysis-nb-server:
    image: farrandi/522-workflows-group-18:main
        ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
